			constexpr auto PrimaryActorTick = 0x28; // FActorTickFunction
			constexpr auto bReplicateMovement = 0x80; // char : 1
			constexpr auto bExchangedRoles = 0x80; // char : 1
			constexpr auto bTearOff = 0x80; // char : 1
			constexpr auto bHidden = 0x80; // char : 1
			constexpr auto bAlwaysRelevant = 0x80; // char : 1
			constexpr auto bOnlyRelevantToOwner = 0x80; // char : 1
			constexpr auto bNetStartup = 0x80; // char : 1
			constexpr auto bNetTemporary = 0x80; // char : 1
			constexpr auto bNetLoadOnClient = 0x81; // char : 1
			constexpr auto bRelevantForNetworkReplays = 0x81; // char : 1
			constexpr auto bRelevantForLevelBounds = 0x81; // char : 1
			constexpr auto bReplayRewindable = 0x81; // char : 1
			constexpr auto bAllowTickBeforeBeginPlay = 0x81; // char : 1
			constexpr auto bAutoDestroyWhenFinished = 0x81; // char : 1
			constexpr auto bBlockInput = 0x81; // char : 1
			constexpr auto bNetUseOwnerRelevancy = 0x81; // char : 1
			constexpr auto bEnableAutoLODGeneration = 0x82; // char : 1
			constexpr auto bActorSeamlessTraveled = 0x82; // char : 1
			constexpr auto bIsEditorOnlyActor = 0x82; // char : 1
			constexpr auto bFindCameraComponentWhenViewTarget = 0x82; // char : 1
			constexpr auto bIgnoresOriginShifting = 0x82; // char : 1
			constexpr auto bGenerateOverlapEventsDuringLevelStreaming = 0x82; // char : 1
			constexpr auto bCollideWhenPlacing = 0x82; // char : 1
			constexpr auto bCanBeDamaged = 0x82; // char : 1
			constexpr auto bReplicates = 0x83; // char : 1
			constexpr auto bCanBeInCluster = 0x83; // char : 1
			constexpr auto bAllowReceiveTickEventOnDedicatedServer = 0x83; // char : 1
			constexpr auto bActorIsBeingDestroyed = 0x84; // char : 1
			constexpr auto bActorEnableCollision = 0x84; // char : 1
			constexpr auto RemoteRole = 0x85; // ENetRole
			constexpr auto ReplicatedMovement = 0x88; // FRepMovement
			constexpr auto InitialLifeSpan = 0xbc; // float
			constexpr auto CustomTimeDilation = 0xc0; // float
			constexpr auto AttachmentReplication = 0xc8; // FRepAttachment
			constexpr auto Owner = 0x108; // AActor*
			constexpr auto NetDriverName = 0x110; // FName
			constexpr auto Role = 0x118; // ENetRole
			constexpr auto NetDormancy = 0x119; // ENetDormancy
			constexpr auto SpawnCollisionHandlingMethod = 0x11a; // ESpawnActorCollisionHandlingMethod
			constexpr auto AutoReceiveInput = 0x11b; // EAutoReceiveInput
			constexpr auto InputPriority = 0x11c; // int32_t
			constexpr auto InputComponent = 0x120; // UInputComponent*
			constexpr auto NetCullDistanceSquared = 0x128; // float
			constexpr auto NetTag = 0x12c; // int32_t
			constexpr auto NetUpdateFrequency = 0x130; // float
			constexpr auto MinNetUpdateFrequency = 0x134; // float
			constexpr auto bUseOwnerRelativeNetUpdateFrequency = 0x138; // char : 1
			constexpr auto bUseRelativeNetUpdateFrequency = 0x138; // char : 1
			constexpr auto MinRelativeNetUpdateEvaluationFrequency = 0x13c; // float
			constexpr auto NetPriority = 0x140; // float
			constexpr auto Instigator = 0x148; // APawn*
			constexpr auto Children = 0x150; // TArray<AActor*>
			constexpr auto RootComponent = 0x160; // USceneComponent*
			constexpr auto ControllingMatineeActors = 0x168; // TArray<AMatineeActor*>
			constexpr auto Layers = 0x180; // TArray<FName>
			constexpr auto ParentComponent = 0x190; // TWeakObjectPtr<UChildActorComponent>
			constexpr auto Tags = 0x198; // TArray<FName>
			constexpr auto OnTakeAnyDamage = 0x1a8; // FScriptMulticastDelegate
			constexpr auto OnTakePointDamage = 0x1a9; // FScriptMulticastDelegate
			constexpr auto OnTakeRadialDamage = 0x1aa; // FScriptMulticastDelegate
			constexpr auto OnActorBeginOverlap = 0x1ab; // FScriptMulticastDelegate
			constexpr auto OnActorEndOverlap = 0x1ac; // FScriptMulticastDelegate
			constexpr auto OnBeginCursorOver = 0x1ad; // FScriptMulticastDelegate
			constexpr auto OnEndCursorOver = 0x1ae; // FScriptMulticastDelegate
			constexpr auto OnClicked = 0x1af; // FScriptMulticastDelegate
			constexpr auto OnReleased = 0x1b0; // FScriptMulticastDelegate
			constexpr auto OnInputTouchBegin = 0x1b1; // FScriptMulticastDelegate
			constexpr auto OnInputTouchEnd = 0x1b2; // FScriptMulticastDelegate
			constexpr auto OnInputTouchEnter = 0x1b3; // FScriptMulticastDelegate
			constexpr auto OnInputTouchLeave = 0x1b4; // FScriptMulticastDelegate
			constexpr auto OnActorHit = 0x1b5; // FScriptMulticastDelegate
			constexpr auto OnDestroyed = 0x1b6; // FScriptMulticastDelegate
			constexpr auto OnEndPlay = 0x1b7; // FScriptMulticastDelegate
			constexpr auto InstanceComponents = 0x218; // TArray<UActorComponent*>
			constexpr auto BlueprintCreatedComponents = 0x228; // TArray<UActorComponent*>
			constexpr auto bStopAILogicOnUnposses = 0x2f8; // char : 1
			constexpr auto bLOSflag = 0x2f8; // char : 1
			constexpr auto bSkipExtraLOSChecks = 0x2f8; // char : 1
			constexpr auto bAllowStrafe = 0x2f8; // char : 1
			constexpr auto bWantsPlayerState = 0x2f8; // char : 1
			constexpr auto bSetControlRotationFromPawnOrientation = 0x2f8; // char : 1
			constexpr auto PathFollowingComponent = 0x300; // UPathFollowingComponent*
			constexpr auto BrainComponent = 0x308; // UBrainComponent*
			constexpr auto PerceptionComponent = 0x310; // UAIPerceptionComponent*
			constexpr auto ActionsComp = 0x318; // UPawnActionsComponent*
			constexpr auto Blackboard = 0x320; // UBlackboardComponent*
			constexpr auto CachedGameplayTasksComponent = 0x328; // UGameplayTasksComponent*
			constexpr auto DefaultNavigationFilterClass = 0x330; // UNavigationQueryFilter*
			constexpr auto ReceiveMoveCompleted = 0x338; // FScriptMulticastDelegate
			constexpr auto SelectionMode = 0x2c8; // ESelectionMode
			constexpr auto ConsumeMouseWheel = 0x2c9; // EConsumeMouseWheel
			constexpr auto bClearSelectionOnClick = 0x2ca; // bool
			constexpr auto bIsFocusable = 0x2cb; // bool
			constexpr auto EntrySpacing = 0x2cc; // float
			constexpr auto bReturnFocusToSelection = 0x2d0; // bool
			constexpr auto ListItems = 0x2d8; // TArray<UObject*>
			constexpr auto BP_OnEntryInitialized = 0x2f8; // FScriptMulticastDelegate
			constexpr auto BP_OnItemClicked = 0x308; // FScriptMulticastDelegate
			constexpr auto BP_OnItemDoubleClicked = 0x318; // FScriptMulticastDelegate
			constexpr auto BP_OnItemIsHoveredChanged = 0x328; // FScriptMulticastDelegate
			constexpr auto BP_OnItemSelectionChanged = 0x338; // FScriptMulticastDelegate
			constexpr auto BP_OnItemScrolledIntoView = 0x348; // FScriptMulticastDelegate
			constexpr auto EntryWidgetClass = 0x108; // UUserWidget*
			constexpr auto BP_OnEntryGenerated = 0x110; // FScriptMulticastDelegate
			constexpr auto BP_OnEntryReleased = 0x120; // FScriptMulticastDelegate
			constexpr auto EntryWidgetPool = 0x130; // FUserWidgetPool
			constexpr auto ViewportClient = 0x70; // UGameViewportClient*
			constexpr auto AspectRatioAxisConstraint = 0x94; // EAspectRatioAxisConstraint
			constexpr auto PendingLevelPlayerControllerClass = 0x98; // APlayerController*
			constexpr auto bSentSplitJoin = 0xa0; // char : 1
			constexpr auto ControllerId = 0xe0; // int32_t
			constexpr auto UberGraphFrame = 0x2a0; // FPointerToUberGraphFrame
			constexpr auto AnimGraphNode_Root_181E1165464545EE1AF5899DFF1F0C83 = 0x2a8; // FAnimNode_Root
			constexpr auto AnimGraphNode_Slot_42C861164D7CA3282FED84940A4B3534 = 0x2d8; // FAnimNode_Slot
			constexpr auto AnimGraphNode_SequencePlayer_8A0623B441EE0EB65533898000B50487 = 0x320; // FAnimNode_SequencePlayer
			constexpr auto UberGraphFrame = 0x2b0; // FPointerToUberGraphFrame
			constexpr auto AnimGraphNode_Root_1E7BFCAC49FD8F000ECD698E7500642B = 0x2b8; // FAnimNode_Root
			constexpr auto AnimGraphNode_LayeredBoneBlend_713165C84E86481A728A33974A97D2D6 = 0x2e8; // FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_SequencePlayer_11EFBDAE4123E1FADC88DEA0BDABF42E = 0x3a8; // FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_Slot_E97FE6554F95354F27D45289B9E73F4C = 0x420; // FAnimNode_Slot
			constexpr auto AnimGraphNode_Slot_394FFA9C4E9E50BA347B05A6717932B4 = 0x468; // FAnimNode_Slot
			constexpr auto AnimGraphNode_Slot_47F41BDE4B08D92097533FAE2CE370DF = 0x4b0; // FAnimNode_Slot
			constexpr auto AnimGraphNode_SequencePlayer_E04309E04FD6E4C8DE6EAF988926AAE1 = 0x4f8; // FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_LayeredBoneBlend_376E88EB4DDDD114A338DF9722B61097 = 0x570; // FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_LocalRefPose_73B93062438C3A22A1BF16817A63EF3C = 0x630; // FAnimNode_RefPose
			constexpr auto AnimGraphNode_LayeredBoneBlend_C69C586C4FF72B9C6C2BD6A3426FE07C = 0x648; // FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_SequenceEvaluator_AAAF011746C6F60E95E998B2E3B20026 = 0x708; // FAnimNode_SequenceEvaluator
			constexpr auto AnimGraphNode_ModifyBone_B33957E543AA7B582ABB1084052BE87E = 0x750; // FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ComponentToLocalSpace_8B14D2CA45A795CE19D38AB30D180786 = 0x858; // FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_LocalToComponentSpace_30338B064A52C59065B95D8DC586D688 = 0x878; // FAnimNode_ConvertLocalToComponentSpace
			constexpr auto LadderScaleAds = 0x898; // FVector
			constexpr auto UberGraphFrame = 0x2b0; // FPointerToUberGraphFrame
			constexpr auto AnimGraphNode_Root_4E22333C4FD159D3D996D0967A16B0AC = 0x2b8; // FAnimNode_Root
			constexpr auto AnimGraphNode_LayeredBoneBlend_A974982043B6298A868B1C942AA8EA9C = 0x2e8; // FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_SequencePlayer_CF95F4B44611F1462B2095B3E440C38A = 0x3a8; // FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_Slot_A48FCBEF444CA4C289F4779D93AA50A9 = 0x420; // FAnimNode_Slot
			constexpr auto AnimGraphNode_Slot_0AC39CED49A190B8B33A62BCD4C2AD2E = 0x468; // FAnimNode_Slot
			constexpr auto AnimGraphNode_Slot_226857E8457E7BCA5B4BF7838D497BDA = 0x4b0; // FAnimNode_Slot
			constexpr auto AnimGraphNode_SequencePlayer_CCC48F004E784147E143C0951AE05EC9 = 0x4f8; // FAnimNode_SequencePlayer
			constexpr auto UberGraphFrame = 0x230; // FPointerToUberGraphFrame
			constexpr auto AmmoAmount = 0x238; // UImage*
			constexpr auto ConstructionAmount = 0x240; // UImage*
			constexpr auto EmptyAmount = 0x248; // UImage*
			constexpr auto H_Ammo = 0x250; // UHorizontalBox*
			constexpr auto H_Construction = 0x258; // UHorizontalBox*
			constexpr auto Image_1 = 0x260; // UImage*
			constexpr auto Image_2 = 0x268; // UImage*
			constexpr auto SizeBox_Parent = 0x270; // USizeBox*
			constexpr auto TB_AmmoAmount = 0x278; // UTextBlock*
			constexpr auto TB_ConstructionAmount = 0x280; // UTextBlock*
			constexpr auto TB_Max = 0x288; // UTextBlock*
			constexpr auto WeaponName = 0x290; // UTextBlock*
			constexpr auto Ammo = 0x298; // float
			constexpr auto Construction = 0x29c; // float
			constexpr auto TotalPoints = 0x2a0; // float
			constexpr auto HasAmmoWeapon = 0x2a4; // bool
			constexpr auto HasConstructionWeapon = 0x2a5; // bool
			constexpr auto MyPC = 0x2a8; // ASQPlayerController*
			constexpr auto CurrentSeat = 0x2b0; // USQVehicleSeatComponent*
			constexpr auto VehicleResourceInventory = 0x2b8; // USQVehicleResourceWeaponInventoryComponent*
			constexpr auto UberGraphFrame = 0x230; // FPointerToUberGraphFrame
			constexpr auto AmphibiousImage = 0x238; // UImage*
			constexpr auto AmphibiousIndicator = 0x240; // UOverlay*
			constexpr auto Border_Amphibiouis = 0x248; // UBorder*
			constexpr auto Border_Gear = 0x250; // UBorder*
			constexpr auto Border_Handbrake = 0x258; // UBorder*
			constexpr auto DialNumParent = 0x260; // UCanvasPanel*
			constexpr auto FrontImage = 0x268; // UImage*
			constexpr auto HandBrake = 0x270; // UOverlay*
			constexpr auto HandbrakeImage = 0x278; // UImage*
			constexpr auto Image_1 = 0x280; // UImage*
			constexpr auto PitchParent = 0x288; // UOverlay*
			constexpr auto RearmBox = 0x290; // UHorizontalBox*
			constexpr auto REVs = 0x298; // UImage*
			constexpr auto RollParent = 0x2a0; // UOverlay*
			constexpr auto SecundaryDisplay = 0x2a8; // UOverlay*
			constexpr auto SideImage = 0x2b0; // UImage*
			constexpr auto SpeedArrow = 0x2b8; // UImage*
			constexpr auto SpeedParent = 0x2c0; // UOverlay*
			constexpr auto TB_Cost = 0x2c8; // UTextBlock*
			constexpr auto TB_Gear = 0x2d0; // UTextBlock*
			constexpr auto MyVehicle = 0x2d8; // ASQGroundVehicle*
			constexpr auto Speed = 0x2e0; // float
			constexpr auto RPM = 0x2e4; // float
			constexpr auto WarningRoll = 0x2e8; // float
			constexpr auto WarningPitch = 0x2ec; // float
			constexpr auto MI_Revs = 0x2f0; // UMaterialInstanceDynamic*
			constexpr auto RevsPercent = 0x2f8; // float
			constexpr auto MyPC = 0x300; // ASQPlayerController*
			constexpr auto MyPS = 0x308; // ASQPlayerState*
			constexpr auto DefaultFrontImage = 0x310; // UTexture2D*
			constexpr auto DefaultSideImage = 0x318; // UTexture2D*
			constexpr auto MySoldier = 0x320; // ASQSoldierNew*
			constexpr auto RefreshTimer = 0x328; // FTimerHandle
			constexpr auto HandbrakeOnColor = 0x330; // FSlateColor
			constexpr auto HandbrakeOffColor = 0x358; // FSlateColor
			constexpr auto AmphibiousOnColor = 0x380; // FSlateColor
			constexpr auto AmphibiousOffColor = 0x3a8; // FSlateColor
